service: teachosm-geosurge-image-upload
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline #serverless-offline needs to be last in the list

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage}
  deploymentBucket:
    name: teachosm-geosurge-serverless-s3upload-${opt:stage}
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::teachosm-geosurge-content-uploads-${opt:stage}/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::teachosm-geosurge-project-pics-${opt:stage}/*"


# Expose function to public API for POST requests.
functions:
  requestUploadURL_pics:
    handler: handler.requestUploadURL_pics
    events:
      - http:
          path: requestUploadURL_pics
          method: post
          cors: true
  requestUploadURL_content:
    handler: handler.requestUploadURL_content
    events:
      - http:
          path: requestUploadURL_content
          method: post
          cors: true

