service: teachosm-geosurge-image-upload

plugins:
  - serverless-dotenv-plugin
  - serverless-offline #serverless-offline needs to be last in the list

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  deploymentBucket:
    name: teachosm-geosurge-serverless-s3upload-${env:STAGE}
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${env:CONTENT_UPLOADS_BUCKET}-${env:STAGE}/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${env:PICS_UPLOADS_BUCKET}-${env:STAGE}/*"


# Expose function to public API for POST requests.
functions:
  requestUploadURL_pics:
    handler: handler.requestUploadURL_pics
    events:
      - http:
          path: requestUploadURL_pics
          method: post
          cors: true
  requestUploadURL_content:
    handler: handler.requestUploadURL_content
    events:
      - http:
          path: requestUploadURL_content
          method: post
          cors: true

