# serverless.yml

service: teachosm-geosurge-convert-post
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  bucket: ${env:PROJECT_POSTS_BUCKET}-${opt:stage}

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}-${opt:stage}
  region: us-east-1
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${env:PROJECT_POSTS_BUCKET}-${opt:stage}/*"

functions:
  app:
    handler: index.handler
    events:
      - http: 
            path: /
            method: any
      - http: 
            path: '{proxy+}'
            method: any
  getPost:
    handler: index.handler
    events:
      - http: 
            path: '/posts/{proxy+}'
            method: get
  createPost:
    handler: index.handler
    events:
      - http: 
            path: /posts
            method: post
            cors: true




